import { describe, expect, it } from 'vitest';
import { runRepositoryExplorer } from '../../client/src/agents/repositoryExplorer.agent';
import { runRootCauseInvestigator } from '../../client/src/agents/rootCauseInvestigator.agent';
import { runFixPlanner } from '../../client/src/agents/fixPlanner.agent';
import { runFixer } from '../../client/src/agents/fixer.agent';
import { runVerification } from '../../client/src/agents/verification.agent';
import { Orchestrator } from '../../client/src/agents/orchestrator';
import { demoRepository, demoProblem, seededInvestigations } from '../../client/src/mocks/data';
import type { Investigation } from '../../client/src/types';

describe('DevFix demo agent chain', () => {
  it('passes structured output between all five agents', () => { const explorer = runRepositoryExplorer(demoRepository, demoProblem); const root = runRootCauseInvestigator(demoProblem, explorer); const plan = runFixPlanner(root, explorer); const fixer = runFixer(plan); const verification = runVerification(); expect(explorer.relevantFiles).toContain('src/auth/tokenManager.ts'); expect(root.confidence).toBeGreaterThan(.9); expect(plan.steps.length).toBeGreaterThan(3); expect(fixer.diff.length).toBe(3); expect(verification.overall).toBe('verified'); });
  it('seeds one repository with the three distinct demo investigations', () => { expect(demoRepository.name).toBe('acme-corp/api-gateway'); expect(seededInvestigations).toHaveLength(3); expect(seededInvestigations.map((item) => item.problem.title)).toEqual(['Intermittent 401 Unauthorized after token refresh', 'Checkout fails when the cart is empty', 'Slow API response during product search']); expect(new Set(seededInvestigations.map((item) => item.repositoryId))).toEqual(new Set([demoRepository.id])); });
  it('runs fixer and verification after an approved plan', async () => { const explorer = runRepositoryExplorer(demoRepository, demoProblem); const rootCause = runRootCauseInvestigator(demoProblem, explorer); const fixPlan = runFixPlanner(rootCause, explorer); const investigation: Investigation = { id: 'workflow-test', repositoryId: demoRepository.id, problem: demoProblem, status: 'approved', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), explorer, rootCause, fixPlan, activities: [{ key: 'repo-explorer', name: 'Repository Explorer', status: 'completed', description: 'Repository analyzed' }, { key: 'root-cause', name: 'Root Cause Investigator', status: 'completed', description: 'Root cause identified' }, { key: 'fix-planner', name: 'Fix Planner', status: 'completed', description: 'Fix plan created' }, { key: 'approval', name: 'Developer Approval', status: 'completed', description: 'Fix approved by developer' }, { key: 'fixer', name: 'Fixer Agent', status: 'pending', description: 'Waiting for approval' }, { key: 'verification', name: 'Verification Agent', status: 'pending', description: 'Waiting for changes to be applied' }] }; const orchestrator = new Orchestrator(); const statuses: string[] = []; const afterApply = await orchestrator.apply(investigation, (next) => statuses.push(`${next.activities.find((activity) => activity.key === 'fixer')?.status}:${next.status}`)); const verified = await orchestrator.verify(afterApply, (next) => statuses.push(`${next.activities.find((activity) => activity.key === 'verification')?.status}:${next.status}`)); expect(statuses).toEqual(['running:applying', 'completed:approved', 'running:verifying', 'completed:verified']); expect(verified.status).toBe('verified'); expect(verified.fixer?.diff).toHaveLength(3); expect(verified.verification?.overall).toBe('verified'); expect(verified.finalReport?.summary).toContain('all verification checks passed'); });
});
