import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { Investigation, Problem, WorkflowState } from '../types';
import { demoRepository, seededInvestigations } from '../mocks/data';
import { loadState, saveState } from '../services/storage.service';
import { agentService } from '../services/agent.service';
interface SessionContextValue extends WorkflowState { active?: Investigation; loadDemo: () => void; createInvestigation: (repositoryId: string, problem: Problem) => Investigation; updateInvestigation: (investigation: Investigation) => void; runDiscovery: (id: string) => Promise<void>; approveFix: (id: string) => void; applyFix: (id: string) => Promise<void>; verifyFix: (id: string) => Promise<void>; }
const SessionContext = createContext<SessionContextValue | null>(null);
const initial: WorkflowState = { repositories: [demoRepository], investigations: seededInvestigations };
export function SessionProvider({ children }: { children: React.ReactNode }) { const [state, setState] = useState<WorkflowState>(() => loadState(initial)); useEffect(() => saveState(state), [state]); const active = state.investigations.find((i) => i.id === state.activeInvestigationId);
  const updateInvestigation = (investigation: Investigation) => setState((s) => ({ ...s, investigations: s.investigations.map((i) => i.id === investigation.id ? investigation : i), activeInvestigationId: investigation.id }));
  const value = useMemo<SessionContextValue>(() => ({ ...state, active, loadDemo: () => setState((s) => ({ ...s, activeInvestigationId: 'demo-401' })), createInvestigation: (repositoryId, problem) => { const id = `inv-${Date.now()}`; const investigation: Investigation = { id, repositoryId, problem, status: 'draft', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), activities: [{ key: 'repo-explorer', name: 'Repository Explorer', status: 'pending', description: 'Waiting to analyze repository structure' }, { key: 'root-cause', name: 'Root Cause Investigator', status: 'pending', description: 'Waiting for repository context' }, { key: 'fix-planner', name: 'Fix Planner', status: 'pending', description: 'Waiting for root cause analysis' }, { key: 'approval', name: 'Developer Approval', status: 'waiting', description: 'Review the proposed implementation' }, { key: 'fixer', name: 'Fixer Agent', status: 'pending', description: 'Waiting for approval' }, { key: 'verification', name: 'Verification Agent', status: 'pending', description: 'Waiting for changes to be applied' }] }; setState((s) => ({ ...s, investigations: [investigation, ...s.investigations], activeInvestigationId: id })); return investigation; }, updateInvestigation, runDiscovery: async (id) => { const current = state.investigations.find((i) => i.id === id); if (current) await agentService.discover(current, updateInvestigation); }, approveFix: (id) => { const current = state.investigations.find((i) => i.id === id); if (!current) return; updateInvestigation({ ...current, status: 'approved', activities: current.activities.map((a) => a.key === 'approval' ? { ...a, status: 'completed', description: 'Fix approved by developer' } : a) }); }, applyFix: async (id) => { const current = state.investigations.find((i) => i.id === id); if (current) await agentService.apply(current, updateInvestigation); }, verifyFix: async (id) => { const current = state.investigations.find((i) => i.id === id); if (current) await agentService.verify(current, updateInvestigation); } }), [state, active]); return <SessionContext.Provider value={value}>{children}</SessionContext.Provider>; }
export function useSession() { const ctx = useContext(SessionContext); if (!ctx) throw new Error('useSession must be used inside SessionProvider'); return ctx; }
